function Arrow(){return <span className="arrow">↗</span>}
function Seesaw(){return <div className="seesaw" aria-label="A seesaw representing send and receive"><div className="seesaw-label seesaw-label-left">SEND</div><div className="seesaw-label seesaw-label-right">RECEIVE</div><div className="seesaw-arm"><span className="seesaw-end seesaw-end-left"/><span className="seesaw-end seesaw-end-right"/></div><div className="seesaw-pivot"/></div>}
function Term({lines}:{lines:[string,string?][]}){return <div className="terminal">{lines.map(([cmd,note],i)=><div key={i}><span className="tp">$</span> {cmd}{note?<span className="tc">  # {note}</span>:null}</div>)}</div>}
export default function Home(){return <main>
<nav className="nav shell"><a className="wordmark" href="#">WIPPLANK<span className="wordmark-dot">.</span></a><div className="nav-links"><a href="#how-it-works">How it works</a><a href="#features">Features</a><a href="#open-source">Open source</a><a className="nav-github" href="https://github.com/" target="_blank" rel="noreferrer">GitHub <Arrow/></a></div></nav>
<section className="hero shell"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-mark"/> TERMINAL-FIRST EMAIL</div><h1>EMAIL FOR<br/>HUMANS <span className="amp">&amp;</span> AGENTS.</h1><p className="hero-lede">IMAP and Gmail, multiple accounts, from your terminal. Human-friendly output, <code>--json</code> on everything, and an MCP server so your agent can read and send on your behalf. No boring email allowed.</p><div className="hero-actions"><a className="button button-primary" href="#get-started">Get started <Arrow/></a><a className="button button-secondary" href="https://github.com/" target="_blank" rel="noreferrer">View on GitHub <Arrow/></a></div><Term lines={[["uv run wipplank --backend demo check","zero setup, try it now"],["uv run wipplank party","no boring email"]]}/></div><div className="hero-artwork-wrap"><div className="hero-artwork-frame"><img src="/wipplank-agents-seesaw.png" alt="Two friendly AI agents exchanging email on a seesaw"/></div><div className="hero-artwork-caption"><span>HUMAN ↔ AGENT</span><span>EMAIL IN BOTH DIRECTIONS</span></div></div></section>
<section className="section shell" id="how-it-works"><div className="section-kicker">01 / HOW IT WORKS</div><div className="interface-heading"><h2>Zero to inbox in<br/><em>five commands.</em></h2><p>Try it with the demo backend — no account needed. Connect your real mailbox when you are ready. First sends are dry-runs, so nothing leaves by accident.</p></div><Term lines={[["uv sync --python 3.11 --all-extras","install"],["uv run wipplank --backend demo check","try it, zero setup"],["uv run wipplank auth login --account work --preset fastmail","connect your mailbox"],["uv run wipplank check","your inbox"],["uv run wipplank send --to bob@example.com -s \"hi\" --body \"hello\" --dry-run","safe first send"]]}/></section>
<section className="exchange section shell"><div className="section-kicker">02 / THE NAME</div><div className="name-card"><div className="name-main"><div className="name-word">wipplank<span>.</span></div><div className="name-meta"><span>AFRIKAANS</span><span>noun</span></div><div className="name-definition">seesaw</div></div><div className="name-story"><div className="story-mark">↔</div><h2>Email goes<br/><em>both ways.</em></h2><p>Send. Receive. Reply. Repeat. One side goes up while the other comes down. <strong>Wipplank</strong> is a simple name for a two-way conversation.</p><div className="exchange-flow"><span>send</span><i></i><b>↔</b><i></i><span>receive</span></div></div></div></section>
<section className="interface section shell"><div className="section-kicker">03 / ONE SYSTEM</div><div className="interface-heading"><h2>One email system.<br/><em>Three ways to use it.</em></h2><p>The same engine serves a person at a keyboard, a script in cron, and an agent running in the background.</p></div><div className="interface-grid">
{[['01','⌁','TUI','A full inbox without leaving your terminal — read, star, search, compose.','wipplank tui','FOR YOUR KEYBOARD'],['02','>_','CLI','Composable commands for scripts and automation. --json on everything.','wipplank send --dry-run --json','FOR YOUR SCRIPTS'],['03','◎','MCP','Controlled agent access: list, read, search, send, reply — plus backend status.','wipplank mcp','FOR YOUR AGENTS']].map(([i,icon,title,desc,cmd,aud])=><article className="interface-card" key={title}><div className="card-index">{i}</div><div className="card-icon">{icon}</div><h3>{title}</h3><p>{desc}</p><code>{cmd}</code><div className="card-line"/><span className="card-audience">{aud}</span></article>)}
</div></section>
<section className="architecture section shell"><div className="section-kicker">04 / UNDER THE HOOD</div><div className="architecture-layout"><div><h2>Built for the<br/><em>terminal age.</em></h2><p>Wipplank keeps the core email engine independent from how you interact with it. Stable message IDs, a fast local cache, and read-only-by-default access keep every interface honest.</p></div><div className="architecture-diagram"><div className="arch-core"><small>WIPPLANK</small><strong>EMAIL ENGINE</strong></div><div className="arch-line"/><div className="arch-nodes"><div><b>CLI</b><span>scripts</span></div><div><b>TUI</b><span>humans</span></div><div><b>MCP</b><span>agents</span></div></div></div></div></section>
<section className="features section shell" id="features"><div className="feature-grid">{[['01','Multi-account','IMAP and Gmail side by side, switched with --account.'],['02','Safe reads','BODY.PEEK only. Checking mail never marks it read.'],['03','Keyring secrets','Passwords and tokens live in the OS keyring, never on disk.'],['04','Agent-native','Every command speaks --json; the MCP server speaks agent.'],['05','Fast cache','Repeat checks served locally. --fresh when you want live.'],['06','PGP','Body-only sign and encrypt, verify footer on read.'],['07','Compose kit','Templates, signatures, drafts, saved searches.'],['08','Fun included','Moods, celebrations, Boredom Patrol. Try wipplank party.']].map(([n,t,d])=><div className="feature" key={t}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
<section className="section shell"><div className="section-kicker">05 / IN YOUR TERMINAL</div><div className="cmds">{['check','read','search','send','reply','forward','mark','saved','attach','template','draft','tui','mcp','party','auth'].map((c)=><span key={c}>{c}</span>)}</div></section>
<section className="cta section shell" id="get-started"><div className="cta-inner"><div className="eyebrow"><span className="eyebrow-mark"/> OPEN SOURCE</div><h2>Give your terminal<br/>an <em>inbox.</em></h2><p>For terminal dwellers, script automators, and agent operators. MIT-licensed and tested — no boring email allowed.</p><div className="hero-actions"><a className="button button-primary" href="https://github.com/" target="_blank" rel="noreferrer">View the project <Arrow/></a></div></div></section>
<footer className="footer shell" id="open-source"><div><a className="wordmark" href="#">WIPPLANK<span className="wordmark-dot">.</span></a><p>Email for humans and agents.</p></div><div className="footer-right"><span>Born in South Africa. Built for everywhere.</span><a href="https://github.com/" target="_blank" rel="noreferrer">GitHub <Arrow/></a></div></footer>
</main>}
